module.exports = [
    {
        name: 'Adobo',
        ingredients: ['Pork', 'Garlic', 'Soy Sauce', 'Pepper', 'Vinegar', 'Laurel Leaves'],
        recipeURL: 'https://panlasangpinoy.com/filipino-food-pork-adobo-recipe/',
        imageURL: 'https://images.pexels.com/photos/6896058/pexels-photo-6896058.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Meatballs',
        ingredients: ['Beef', 'Bread Crumbs', 'Milk', 'Salt', 'Pepper', 'Onion', 'Egg'],
        recipeURL: 'https://www.bettycrocker.com/recipes/classic-meatballs/2959910f-1b27-438a-9085-d40b1950db20',
        imageURL: 'https://images.pexels.com/photos/6607386/pexels-photo-6607386.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'French Toast',
        ingredients: ['Egg', 'Milk', 'Sugar', 'Salt', 'Bread'],
        recipeURL: 'https://www.tasteofhome.com/recipes/vanilla-french-toast/',
        imageURL: 'https://images.pexels.com/photos/4676399/pexels-photo-4676399.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Spaghetti',
        ingredients: ['Beef', 'Sausage', 'Onion', 'Tomato', 'Sugar', 'Salt', 'Pepper', 'Spaghetti'],
        recipeURL: 'https://www.tasteofhome.com/recipes/stamp-of-approval-spaghetti-sauce/',
        imageURL: 'https://images.pexels.com/photos/41194/beef-cheese-cuisine-delicious-41194.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Fruit Salad',
        ingredients: ['Pineapple', 'Banana', 'Grape', 'Orange', 'Apple', 'Kiwi'],
        recipeURL: 'https://www.tasteofhome.com/recipes/brunch-fruit-salad/',
        imageURL: 'https://images.pexels.com/photos/1436062/pexels-photo-1436062.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Chili',
        ingredients: ['Beef', 'Onion', 'Garlic', 'Tomato', 'Bell Pepper', 'Beans', 'Chili Powder', 'Salt'],
        recipeURL: 'https://www.tasteofhome.com/recipes/bean-beef-slow-cooked-chili/',
        imageURL: 'https://images.pexels.com/photos/4194622/pexels-photo-4194622.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Garlic Bread',
        ingredients: ['Butter', 'Garlic', 'Bread'],
        recipeURL: 'https://www.tasteofhome.com/recipes/garlic-bread/',
        imageURL: 'https://images.pexels.com/photos/4117707/pexels-photo-4117707.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Steak',
        ingredients: ['Beef', 'Salt', 'Pepper', 'Butter', 'Garlic'],
        recipeURL: 'https://natashaskitchen.com/perfect-grilled-steak/',
        imageURL: 'https://images.pexels.com/photos/3535383/pexels-photo-3535383.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Fried Chicken',
        ingredients: ['Chicken', 'Flour', 'Salt', 'Pepper', 'Egg', 'Salt'],
        recipeURL: 'https://www.tasteofhome.com/recipes/crispy-fried-chicken/',
        imageURL: 'https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Mashed Potatoes',
        ingredients: ['Potato', 'Butter', 'Sour Cream', 'Milk', 'Salt', 'Pepper', 'Nutmeg', 'Bacon'],
        recipeURL: 'https://www.tasteofhome.com/recipes/smashed-potatoes/',
        imageURL: 'https://cdn.pixabay.com/photo/2016/08/08/20/41/burning-love-1579245_1280.jpg',
    },
    {
        name: 'Yogurt Parfait',
        ingredients: ['Apple Sauce', 'Nutmeg', 'Raisin', 'Yogurt'],
        recipeURL: 'https://www.tasteofhome.com/recipes/apple-yogurt-parfaits/',
        imageURL: 'https://images.pexels.com/photos/704971/pexels-photo-704971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Fajitas',
        ingredients: ['Chicken', 'Tomato', 'Bell Pepper', 'Onion', 'Chili Powder', 'Salt'],
        recipeURL: 'https://www.tasteofhome.com/recipes/baked-chicken-fajitas/',
        imageURL: 'https://cdn.pixabay.com/photo/2021/01/20/04/22/fajitas-5933057_1280.jpg',
    },
    {
        name: 'French Fries',
        ingredients: ['Potato', 'Salt', 'Garlic Powder', 'Pepper'],
        recipeURL: 'https://www.tasteofhome.com/recipes/garlic-chive-baked-fries/',
        imageURL: 'https://images.pexels.com/photos/1586942/pexels-photo-1586942.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Scrambled Eggs',
        ingredients: ['Egg', 'Evaporated Milk', 'Salt', 'Pepper', 'Cheese'],
        recipeURL: 'https://www.tasteofhome.com/recipes/fluffy-scrambled-eggs/',
        imageURL: 'https://images.pexels.com/photos/6271487/pexels-photo-6271487.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Grilled Cheese Sandwich',
        ingredients: ['Bread', 'Cheese', 'Butter'],
        recipeURL: 'https://www.tasteofhome.com/recipes/super-grilled-cheese-sandwiches/',
        imageURL: 'https://images.pexels.com/photos/5419221/pexels-photo-5419221.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Parmesan Roasted Broccoli',
        ingredients: ['Broccoli', 'Salt', 'Pepper', 'Garlic', 'Cheese'],
        recipeURL: 'https://www.tasteofhome.com/recipes/parmesan-roasted-broccoli/',
        imageURL: 'https://images.pexels.com/photos/6970264/pexels-photo-6970264.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Snack Dip',
        ingredients: ['Cream Cheese', 'Cheese', 'Bread'],
        recipeURL: 'https://www.tasteofhome.com/recipes/beer-dip/',
        imageURL: 'https://images.pexels.com/photos/1200354/pexels-photo-1200354.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Hard Boiled Eggs',
        ingredients: ['Egg'],
        recipeURL: 'https://www.tasteofhome.com/recipes/hard-boiled-eggs/',
        imageURL: 'https://images.pexels.com/photos/806457/pexels-photo-806457.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Breaded Chicken',
        ingredients: ['Ranch Dressing', 'Cornflakes', 'Garlic Powder'],
        recipeURL: 'https://www.tasteofhome.com/recipes/crumb-coated-ranch-chicken/',
        imageURL: 'https://www.foodista.com/sites/default/files/4304807961_9b04a637e3_z.jpg',
    },
    {
        name: 'Baked Potatoes',
        ingredients: ['Butter', 'Cheese'],
        recipeURL: 'https://www.tasteofhome.com/recipes/parmesan-baked-potatoes/',
        imageURL: 'https://images.pexels.com/photos/162763/delicious-garnish-potatoes-fried-162763.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Roasted Cauliflower',
        ingredients: ['Cauliflower', 'Parsley', 'Rosemary', 'Salt'],
        recipeURL: 'https://www.tasteofhome.com/recipes/roasted-herb-lemon-cauliflower/',
        imageURL: 'https://images.pexels.com/photos/6605771/pexels-photo-6605771.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Roast Chicken',
        ingredients: ['Chicken', 'Salt', 'Pepper'],
        recipeURL: 'https://www.tasteofhome.com/recipes/roasted-chicken/',
        imageURL: 'https://images.pexels.com/photos/6163330/pexels-photo-6163330.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Quesadillas',
        ingredients: ['Beans', 'Tomato', 'Onion', 'Tortilla', 'Cheese'],
        recipeURL: 'https://www.tasteofhome.com/recipes/bean-cheese-quesadillas/',
        imageURL: 'https://cdn.pixabay.com/photo/2020/08/14/10/51/quesadilla-5487578_1280.jpg',
    },
    {
        name: 'BLT',
        ingredients: ['Bacon', 'Mayonnaise', 'Vinegar', 'Pepper', 'Salt', 'Bread', 'Tomato'],
        recipeURL: 'https://www.tasteofhome.com/recipes/blt-with-peppered-balsamic-mayo/',
        imageURL: 'https://cdn.pixabay.com/photo/2019/04/20/15/19/bacon-4142058_1280.jpg',
    },
    {
        name: 'Chicken and Pasta',
        ingredients: ['Chicken', 'Pasta', 'Salt', 'Pepper', 'Flour', 'Garlic'],
        recipeURL: 'https://www.tasteofhome.com/recipes/lemon-chicken-pasta/',
        imageURL: 'https://images.pexels.com/photos/2697229/pexels-photo-2697229.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Omelet',
        ingredients: ['Egg', 'Chives', 'Salt', 'Pepper'],
        recipeURL: 'https://www.tasteofhome.com/recipes/cream-cheese-chive-omelet/',
        imageURL: 'https://images.pexels.com/photos/1484526/pexels-photo-1484526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Roasted Green Beans',
        ingredients: ['Green Beans', 'Garlic', 'Salt', 'Pepper'],
        recipeURL: 'https://www.tasteofhome.com/recipes/roasted-green-beans-with-lemon-walnuts/',
        imageURL: 'https://images.pexels.com/photos/3338497/pexels-photo-3338497.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Tacos',
        ingredients: ['Onion', 'Beans', 'Tomato', 'Cabbage', 'Garlic', 'Cheese', 'Chicken'],
        recipeURL: 'https://www.tasteofhome.com/recipes/black-bean-and-corn-tacos/',
        imageURL: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Chicken Stir Fry',
        ingredients: ['Chicken', 'Noodles', 'Bok Choy', 'Bell Pepper', 'Onion', 'Teriyaki Sauce'],
        recipeURL: 'https://www.tasteofhome.com/recipes/chicken-stir-fry-with-noodles/',
        imageURL: 'https://images.pexels.com/photos/4060347/pexels-photo-4060347.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
        name: 'Filipino Spaghetti',
        ingredients: ['Garlic', 'Onion', 'Tomato', 'Beef', 'Tomato Sauce', 'Ketchup', 'Cheese', 'Sugar', 'Hotdog'],
        recipeURL: 'https://www.kawalingpinoy.com/filipino-style-spaghetti/',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Filipino_style_spaghetti.jpg/1200px-Filipino_style_spaghetti.jpg',
    },
]