const meats = [
    'Pork',
    'Beef',
    'Lamb',
    'Chicken',
    'Turkey',
    'Goat',
    'Tuna',
    'Salmon',
    'Mackerel',
    'Cod',
    'Sardines',
    'Bass',
    'Crab',
    'Lobster',
    'Sausage',
    'Bacon',
    'Hotdog',
];
module.exports.meats = meats.sort();

const fruits = [
    'Apple',
    'Apricot',
    'Avocado',
    'Banana',
    'Blackberry',
    'Blueberry',
    'Cherry',
    'Pear',
    "Mango",
    'Peach',
    'Lychee',
    'Watermelon',
    'Guava',
    'Coconut',
    'Onion',
    'Garlic',
    'Potato',
    'Carrot',
    'Broccoli',
    'Spinach',
    'Mushroom',
    'Ginger',
    'Celery',
    'Cucumber',
    'Avocado',
    'Pickle',
    'Cabbage',
    'Olive',
    'Pumpkin',
    'Eggplant',
    'Bell Pepper',
    'Seaweed',
    'Basil',
    'Tomato',
    'Asparagus',
    'Sweet Potato',
    'Pineapple',
    'Grape',
    'Orange',
    'Kiwi',
    'Beans',
    'Apple Sauce',
    'Raisin',
    'Cauliflower',
    'Green Beans',
    'Bok Choy',
];
module.exports.fruits = fruits.sort();

const condiments = [
    'Ketchup',
    'Mayonnaise',
    'Musturd',
    'Vinegar',
    'Soy Sauce',
    'Hot Sauce',
    'Barbecue Sauce',
    'Ranch Dressing',
    'Fish Sauce',
    'Teriyaki Sauce',
    'Steak Sauce',
    'Ponzu',
    'Tomato Sauce',
];
module.exports.condiments = condiments.sort();

const grainsArr = [
    'Rice',
    'Pasta',
    'Flour',
    'Baking Soda',
    'Cornstarch',
    'Noodles',
    'Ramen',
    'Bisquick',
    'Pretzel',
    'Cornbread',
    'Ravioli',
    'Croissants',
    'Starch',
    'Bread Crumbs',
    'Spaghetti',
    'Tortilla',
    'Cornflakes',
];
module.exports.grainsArr = grainsArr.sort();

const dairyArr = [
    'Butter',
    'Egg',
    'Milk',
    'Cheese',
    'Sour Cream',
    'Cream Cheese',
    'Yogurt',
    'Mozzarella',
    'Whipped Cream',
    'Ice Cream',
    'Custard',
    'Evaporated Milk',
];
module.exports.dairyArr = dairyArr.sort();

const seasonings = [
    'Bouillon',
    'Apple Cider',
    'Ground Ginger',
    'Chili Sauce',
    'BBQ Rub',
    'Adobo Seasoning',
    'Mustard Powder',
    'Mango Powder',
    'Matcha Powder',
    'Hoisin Sauce',
    'Wasabi',
    'Cinnamon',
    'Vanilla',
    'Garlic Powder',
    'Paprika',
    'Chili Powder',
    'Cayenne',
    'Nutmeg',
    'Onion Powder',
    'Sage',
    'Steak Seasoning',
    'Saffron',
    'Chipotle',
    'Pepper',
    'Laurel Leaves',
    'Salt',
    'Sugar',
    'Italian Seasoning',
    'Parsley',
    'Chives',
    'Rosemary',
];
module.exports.seasonings = seasonings.sort();